"""empty message

Revision ID: 2c55a9aeeb7e
Revises: ffdaeb3e7357
Create Date: 2023-10-15 17:54:37.280355

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2c55a9aeeb7e'
down_revision = 'ffdaeb3e7357'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('_alembic_tmp_animal')
    with op.batch_alter_table('animal', schema=None) as batch_op:
        batch_op.add_column(sa.Column('age', sa.Integer(), nullable=True))
        batch_op.alter_column('animal_photo',
               existing_type=sa.VARCHAR(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('animal', schema=None) as batch_op:
        batch_op.alter_column('animal_photo',
               existing_type=sa.VARCHAR(),
               nullable=True)
        batch_op.drop_column('age')

    op.create_table('_alembic_tmp_animal',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('animal_type', sa.VARCHAR(), nullable=False),
    sa.Column('name', sa.VARCHAR(), nullable=False),
    sa.Column('birth_date', sa.DATE(), nullable=False),
    sa.Column('breed', sa.VARCHAR(), nullable=False),
    sa.Column('animal_photo', sa.VARCHAR(), nullable=False),
    sa.Column('age', sa.INTEGER(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
