"""empty message

Revision ID: 5ba95d430add
Revises: e08fc0218f8b
Create Date: 2023-10-14 14:38:47.711000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5ba95d430add'
down_revision = 'e08fc0218f8b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('animal', schema=None) as batch_op:
        batch_op.add_column(sa.Column('animal_breed', sa.String(), nullable=False))
        batch_op.add_column(sa.Column('photo', sa.String(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('animal', schema=None) as batch_op:
        batch_op.drop_column('animal_breed')
        batch_op.drop_column('photo')

    # ### end Alembic commands ###
