"""empty message

Revision ID: ffdaeb3e7357
Revises: 18fd26d7c74f
Create Date: 2023-10-15 15:53:48.373797

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ffdaeb3e7357'
down_revision = '18fd26d7c74f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('_alembic_tmp_animal')
    with op.batch_alter_table('animal', schema=None) as batch_op:
        batch_op.add_column(sa.Column('animal_photo', sa.String(), nullable=True))
        batch_op.alter_column('breed',
               existing_type=sa.VARCHAR(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('animal', schema=None) as batch_op:
        batch_op.alter_column('breed',
               existing_type=sa.VARCHAR(),
               nullable=True)
        batch_op.drop_column('animal_photo')

    op.create_table('_alembic_tmp_animal',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('animal_type', sa.VARCHAR(), nullable=False),
    sa.Column('name', sa.VARCHAR(), nullable=False),
    sa.Column('birth_date', sa.DATE(), nullable=False),
    sa.Column('breed', sa.VARCHAR(), nullable=False),
    sa.Column('animal_photo', sa.VARCHAR(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
